-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.profile
(
    id bigserial NOT NULL,
    guild_id bigint,
    user_id bigint NOT NULL,
    xp text NOT NULL DEFAULT 0,
    currency text NOT NULL DEFAULT 0,
    upvotes bigint NOT NULL DEFAULT 0,
    downvotes bigint NOT NULL DEFAULT 0,
    last_action bigint NOT NULL DEFAULT 0,
    last_daily bigint NOT NULL DEFAULT 0,
    daily_streak integer NOT NULL DEFAULT 0,
    max_daily_streak integer NOT NULL DEFAULT 0,
    active_time bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.guild
(
    id bigserial NOT NULL,
    discord_id bigint,
    vote_channels bigint[],
    add_votes boolean NOT NULL DEFAULT False,
    global_economy boolean NOT NULL DEFAULT False,
    global_social boolean NOT NULL DEFAULT False,
    upvote_emoji text,
    downvote_emoji text,
    PRIMARY KEY (guild_id)
    );

CREATE TABLE IF NOT EXISTS public."user"
(
    id bigserial NOT NULL,
    discord_id bigint,
    PRIMARY KEY (id)
    );

ALTER TABLE IF EXISTS public.profile
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.profile
    ADD FOREIGN KEY (guild_id)
    REFERENCES public.guild (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;

END;